# We set the language to python, so that we can more easily specify our
# build matrix.  We simply apt install the compiled dependencies.
language: python

matrix:
  include:
    # GCC 4.8 - this is the default version for many distros
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          packages:
            - build-essential
            - gcc
            - g++
            - gfortran
            - autoconf
            - automake
            - m4
            - libtool
            - libhdf5-dev
            - libmpich-dev
            - mpich
            - fftw3-dev
            - cfitsio-dev
            - libatlas-base-dev
            - pkg-config
      env:
        - MATRIX_EVAL="export CC=$(which gcc) && export CXX=$(which g++) && export FC=$(which gfortran)"
    # GCC 5
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential
            - gcc-5
            - g++-5
            - gfortran-5
            - autoconf
            - automake
            - m4
            - libtool
            - libhdf5-dev
            - libmpich-dev
            - mpich
            - fftw3-dev
            - cfitsio-dev
            - libatlas-base-dev
            - pkg-config
      env:
        - MATRIX_EVAL="export CC=$(which gcc-5) && export CXX=$(which g++-5) && export FC=$(which gfortran-5)"
    # GCC 6
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential
            - gcc-6
            - g++-6
            - gfortran-6
            - autoconf
            - automake
            - m4
            - libtool
            - libhdf5-dev
            - libmpich-dev
            - mpich
            - fftw3-dev
            - cfitsio-dev
            - libatlas-base-dev
            - pkg-config
      env:
        - MATRIX_EVAL="export CC=$(which gcc-6) && export CXX=$(which g++-6) && export FC=$(which gfortran-6)"
    # GCC 7
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential
            - gcc-7
            - g++-7
            - gfortran-7
            - autoconf
            - automake
            - m4
            - libtool
            - libhdf5-dev
            - libmpich-dev
            - mpich
            - fftw3-dev
            - cfitsio-dev
            - libatlas-base-dev
            - pkg-config
      env:
        - MATRIX_EVAL="export CC=$(which gcc-7) && export CXX=$(which g++-7) && export FC=$(which gfortran-7)"

# The versions to test
python:
    - 3.6

# Set up MPI and mpi4py

before_install:
    # set the C and C++ compilers
    - eval "${MATRIX_EVAL}"
    # Information about C and C++ compilers
    - echo "CC = ${CC} $(${CC} -dumpversion)"
    - echo "CXX = ${CXX} $(${CXX} -dumpversion)"
    # set the MPICH underlying compilers
    - export MPICC=$(which mpicc)
    - export MPICXX=$(which mpicxx)
    - export MPICH_CC=${CC}
    - export MPICH_CXX=${CXX}
    # F90 required by libmadam
    - export MPIFC=$(which mpif90)
    - export MPICH_FC=${FC}
    # explicitly set the C and C++ compilers to MPICH compilers for autotools
    - export CC=$(which mpicc)
    - export CXX=$(which mpicxx)
    # information about the MPI compilers
    - echo "MPICC = ${MPICC}"
    - echo "MPICXX = ${MPICXX}"
    - echo "[MPI] CC = ${CC} $(${CC} -dumpversion)"
    - echo "[MPI] CXX = ${CXX} $(${CXX} -dumpversion)"
    - ${MPICC} -v
    - ${MPICXX} -v
    # miniconda install
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    - conda install -c conda-forge numpy scipy matplotlib healpy pyephem pip cython
    - pip install mpi4py
    # Install libsharp C
    - git clone https://github.com/Libsharp/libsharp --branch master --single-branch --depth 1
    - cd libsharp
    - autoreconf
    - ./configure --enable-mpi --enable-pic
    - make
    - export LIBSHARP="$HOME/miniconda"
    - cp -r auto/* $LIBSHARP
    # Install libsharp Python
    - cd python
    - CC="mpicc -g" LDSHARED="mpicc -g -shared" python setup.py install
    - cd ../..
    # Install PySM
    - pip install https://github.com/bthorne93/PySM_public/archive/2.1.0.tar.gz
    # Install libmadam from github master
    - git clone https://github.com/hpc4cmb/libmadam.git --single-branch --depth 1
    - cd libmadam
    - ./autogen.sh
    - export FCFLAGS="-O0 -g -fbounds-check -fPIC"
    - export CFLAGS="-O0 -g -fPIC"
    - ./configure --prefix=$HOME/miniconda
    - make
    - make install
    - cd ..

# Skip this

install:
    # build
    - ./autogen.sh
    - export CFLAGS="-O3 -g -fPIC -pthread -std=c99"
    - export CXXFLAGS="-O3 -g -fPIC -pthread"
    - ./configure --prefix=$HOME/miniconda
    - make
    - make install

# Configure, build, and run tests

script:
    - export OMP_NUM_THREADS=2
    - mpirun -np 4 python -c "import toast.tests; toast.tests.run()"
    - cd examples/; mpirun -np 4 bash run_tiny_tests.sh

# Slack integration

notifications:
    slack: c3cmb:7RR5xHHVvMAuw6g20ZuPhRD3
